# inherit_mode:
#   merge:
#     - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'

# RSpec:
#   Patterns:
#     - 'test/factories'

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/CommentAnnotation:
  Enabled: false

Layout/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  # Max: 100
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Rake/Desc:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashLikeCase:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false